interface Env {
	USERS_DATABASE: D1Database;
	BETTER_AUTH_URL: string;
	SECRET: string;
	AUTH_GITHUB_ID: string;
	AUTH_GITHUB_SECRET: string;
	AUTH_LINUXDO_ID: string;
	AUTH_LINUXDO_SECRET: string;
	LEMONSQUEEZY_CHECKOUT_LINK: string
}